bookcafe/urls.py
from django.contrib import admin
from django.urls import include,path

from .import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from . import views
from accounts.views.views import  LoginView


urlpatterns = [
    path("",views.home,name="home"),
    #path("home",views.home,name="home1"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),#accounts:logout


    path('admin/', admin.site.urls),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('category/', include(('category.urls', 'category'), namespace='category')),

    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('account/', include('accounts.passwords.urls')),
    path('search/', include(('search.urls', 'search'), namespace='search')),


#    path('cat1books/', include(('cat1books.urls', 'cat1books'), namespace='cat1books')),

    # notification part
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),

    path('donation/', include(('donation.urls', 'donation'), namespace='donation')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls','payment')),
    # path('paypal/',include('paypal.standard.ipn.urls')),
    # path('payment/',include('payment.urls','payment')),

    path('tokena/', include(('tokena.urls', 'tokena'), namespace='tokena')),

    path('del_borrower/', include(('del_borrower.urls', 'del_borrower'), namespace='del_borrower')),

    #path('feedback/', include('feedback_form.urls')),
    path('feedback/', include(('feedback_form.urls', 'feedback'), namespace='feedback')),
    path('contact/', include(('contactus.urls', 'contact'), namespace='contact')),

#     path('contactus/', include('contactus.urls'))
# submit
]

if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback_form/urls.py
from django.conf.urls import url

from . import views

app_name = 'form'
urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'', views.feedback_form, name='feedback-page'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

tag/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('hashtag/', views.SearchTag.as_view(),name="ajax_search"),
    path('hashtag.json', views.TagJson.as_view()),
]

feedback_form/models.py
from django.db import models
from django.utils import timezone

class Feedback(models.Model):
    customer_name = models.CharField(max_length=120, null=False)
    email = models.EmailField(max_length=40, null=False)
    comments = models.TextField(null=False)
    book_name = models.CharField(max_length=120, null=False)

    date = models.DateField(auto_now=timezone.now)

    def __str__(self):
        return self.customer_name

feedback_form/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    customer_name = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Fullname',
                'class': 'form-control',
                'rows': '3',
                'id': 'staticEmail'
            }
        )
    )

    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Email (example@gmail.com)',
                'class': 'form-control',
                'id': 'staticEmail'
            }
        )
    )

    comments = forms.CharField(
        label='Feel free to add any other comments or suggestions:',
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Type your suggestions here...',
                'width': '500px',
                'class': 'form-control',
                'oninvalid': 'this.setCustomValidity("Please write your feedback in this field")'
            }
        )
    )

    book_name = forms.CharField(
        label='Feel free to add any other comments or suggestions:',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Book name',
                'width': '500px',
                'class': 'form-control',
                'oninvalid': 'this.setCustomValidity("Please fill this field")'
            }
        )
    )

    class Meta:
        model = Feedback
        fields = ['customer_name', 'email', 'comments', 'book_name']

feedback_form/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .forms import FeedbackForm
from book.models import Book
from django.http import HttpResponse
from .models import *


def home(request):
    return render(request, 'home.html')


def feedback_form(request):
    id = request.POST.get("book_id")
    book = Book.objects.get(id=id)
    print(book.title)
    if request.user.is_authenticated:
        obj = Book.objects.all()
        user = request.user.username
        email = request.user.email
        if request.method == 'POST':
            form = FeedbackForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('form:home')
        else:
            form = FeedbackForm()
        return render(request, 'feedback_form.html', {'form': form, 'user': user, 'email': email ,"object" :book })
    else:
        return redirect('login')

@login_required
def user_logout(request):
    logout(request)
    return redirect('form:home')

feedback_form/templates/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet", href="{% static 'css/feedback_styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>

    {% block title %}{% endblock %}
</head>
<body>
    <div class="container-fluid">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

feedback_form/templates/feedback_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

    <div class="container">
      <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .sign-up{
        background-color: ghostwhite;
    }

    </style>
        <div class="row">
            <div class="col-xl mt-5">
                <form method="POST">
                    {% csrf_token %}

                    <h1 class="heading" style="text-align: center;font-family: 'Lucida Handwriting';">FEEDBACK</h1>

                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Username :</label>
                        <div class="col-sm-10">
                          {{ user }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Email :</label>
                        <div class="col-sm-10">
                          {{ email }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-2 col-form-label">Bookname:</label>
                        <div class="col-sm-10">
                            <input type="text" name="book_name" placeholder="Book name" width="500px" value="{{object.title}}" class="form-control" oninvalid="this.setCustomValidity(&quot;Please fill this field&quot;)" required id="id_book_name" readonly>                        </div>
                    </div>

                    <div class="mt-5 text_area">
                        {{ form.comments|as_crispy_field }}
                    </div>

                    <button type="submit" class="col-md-12 btn btn-info mt-3"><span style="letter-spacing: 1px; word-spacing: 2px">SUBMIT YOUR FEEDBACK</span></button>

                    <div class="col-md-12 mt-5">
                        <a href="{% url 'form:logout' %}">Logout</a>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock  %}

feedback_form/templates/home.html
{% extends 'base.html' %}

{% block body %}

    <h2>Welcome to home</h2>
    {% if user.is_authenticated %}

        <h4>You are logged in</h4>

    {% else %}
        <h4>You are not logged in!!</h4>
        <h5>Please login to give your feedback.</h5>
    {% endif %}

{% endblock body %}

feedback_form/templates/thanks.html
{% extends 'base.html' %}
 
{% block title %}Thanks{% endblock %}
 
{% block body %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'form:feedback-page' %}">Response again?</a></p>
{% endblock %}