accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path,re_path
from django.conf.urls import url

from .views import home1

from .views import views
from .views.students import StudentSignup
from .views.teachers import TeacherSignup
from .views.general import GeneralSignup
urlpatterns = [

    #path('', home1.home, name='home'),
    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$',
            views.AccountEmailActivateView.as_view(),
            name='email-activate'),
    path('studentsignup/', StudentSignup, name="student_signup_new"),
    path('teachersignup/', TeacherSignup, name="teacher_signup_new"),
    path('generalsignup/', GeneralSignup, name="general_signup_new"),

    path('signup/', home1.SignUpView.as_view(),name="signup_all"),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    url(r'^clear/$', views.clear_database, name='clear_database'),
    url(r'^progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    path('borrowed-books/', views.borrowed_books.as_view(), name='borrowed_books'),

]

bookcafe/urls.py
from django.contrib import admin
from django.urls import include,path

from .import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from . import views
from accounts.views.views import  LoginView


urlpatterns = [
    path("",views.home,name="home"),
    #path("home",views.home,name="home1"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),#accounts:logout


    path('admin/', admin.site.urls),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('category/', include(('category.urls', 'category'), namespace='category')),

    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('account/', include('accounts.passwords.urls')),
    path('search/', include(('search.urls', 'search'), namespace='search')),


#    path('cat1books/', include(('cat1books.urls', 'cat1books'), namespace='cat1books')),

    # notification part
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),

    path('donation/', include(('donation.urls', 'donation'), namespace='donation')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls','payment')),
    # path('paypal/',include('paypal.standard.ipn.urls')),
    # path('payment/',include('payment.urls','payment')),

    path('tokena/', include(('tokena.urls', 'tokena'), namespace='tokena')),

    path('del_borrower/', include(('del_borrower.urls', 'del_borrower'), namespace='del_borrower')),

    #path('feedback/', include('feedback_form.urls')),
    path('feedback/', include(('feedback_form.urls', 'feedback'), namespace='feedback')),
    path('contact/', include(('contactus.urls', 'contact'), namespace='contact')),

#     path('contactus/', include('contactus.urls'))
# submit
]

if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name ='payment'
urlpatterns = [
    path('<int:pk>/',views.payment,name="payment"),
    path('paypal-return/',views.paypal_return,name='paypal_return'),
    path('paypal-cancel/',views.paypal_cancel,name="paypal_cancel"),
]

tag/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('hashtag/', views.SearchTag.as_view(),name="ajax_search"),
    path('hashtag.json', views.TagJson.as_view()),
]

accounts/models.py
from datetime import timedelta

from django.conf import settings
from django.urls import reverse

from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.contrib.auth.models import (
    AbstractBaseUser,BaseUserManager
)
from django.template.loader import get_template
from django.utils import timezone

from book.models import Book

from bookcafe.utils import unique_key_generator

DEFAULT_ACTIVATION_DAYS = getattr(settings, 'DEFAULT_ACTIVATION_DAYS', 7)




class UserManager(BaseUserManager):
    def create_user(self,email,first_name=None,password=None,is_active=True,is_staff=False,is_admin=False):
        if not email:
            raise ValueError("users must have email address")
        if not password:
            raise ValueError("users must have a password")
        user_obj = self.model(
            email = self.normalize_email(email),
            first_name=first_name
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.active= is_active
        user_obj.is_active= is_active
        user_obj.admin = is_admin

        user_obj.save(using=self._db)
        return user_obj

    # def create_stffuser
    def create_staffuser(self,email,first_name=None,password=None):
        user = self.create_user(
            email,
            first_name=first_name,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self,email,first_name=None,password=None):
        user = self.create_user(
            email,
            first_name=first_name,
            password=password,
            is_staff=True,
            is_admin=True
        )



class User(AbstractBaseUser):
    username = models.CharField(max_length=255,null=True,blank=True)
    email = models.EmailField(unique=True,max_length=255)
    first_name   = models.CharField(max_length=255, blank=True, null=True)
    last_name   = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    book_issued = models.ManyToManyField(Book,blank=True)
    is_student = models.BooleanField(default=False)
    is_general = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    phone_no=models.IntegerField(blank=True, null=True)
    bio=models.TextField(max_length=255, blank=True, null=True)
    image=models.ImageField(upload_to='profile_image',blank=True, null=True)



    USERNAME_FIELD = 'email'
    #email and password field are required by default

    REQUIRED_FIELDS = []


    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.first_name and self.last_name:
            return self.first_name + self.last_name
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True


    @property
    def is_staff(self):
        return self.staff
    @property
    def is_admin(self):
        return self.admin
    # @property
    # def is_active(self):
    #     return  self.active
    def testinguser(self):
        return '%s, %s, %s' % (self.first_name, self.last_name,self.email)
class EmailActivationQuerySet(models.query.QuerySet):
    def confirmable(self):
        now = timezone.now()
        start_range = now - timedelta(days=DEFAULT_ACTIVATION_DAYS)
        # does my object have a timestamp in here
        end_range = now
        return self.filter(
                activated = False,
                forced_expired = False
              ).filter(
                timestamp__gt=start_range,
                timestamp__lte=end_range
              )


class EmailActivationManager(models.Manager):
    def get_queryset(self):
        return EmailActivationQuerySet(self.model, using=self._db)

    def confirmable(self):
        return self.get_queryset().confirmable()

class EmailActivation(models.Model):
    user            = models.ForeignKey(User,on_delete=models.CASCADE)
    email           = models.EmailField()
    key             = models.CharField(max_length=120, blank=True, null=True)
    activated       = models.BooleanField(default=False)
    forced_expired  = models.BooleanField(default=False)
    expires         = models.IntegerField(default=7) # 7 Days
    timestamp       = models.DateTimeField(auto_now_add=True)
    update          = models.DateTimeField(auto_now=True)

    objects = EmailActivationManager()

    def __str__(self):
        return self.email

    def can_activate(self):
        qs = EmailActivation.objects.filter(pk=self.pk).confirmable()  # 1 object
        if qs.exists():
            return True
        return False

    def activate(self):
        if self.can_activate():
            user = self.user
            user.is_active = True
            user.save()
            self.activated = True
            self.save()
            return True
        return False


    def regenerate(self):
        self.key = None
        self.save()
        if self.key is not None:
            return True
        return False

    def send_activation(self):
        if not self.activated and not self.forced_expired:
            if self.key:
                base_url = getattr(settings, 'BASE_URL', 'python')
                key_path = reverse("accounts:email-activate", kwargs={'key': self.key}) # use reverse
                path = "{base}{path}".format(base=base_url, path=key_path)
                context = {
                    'path': path,
                    'email': self.email
                }
                txt_ = get_template("registration/emails/verify.txt").render(context)
                html_ = get_template("registration/emails/verify.html").render(context)
                subject = '1-Click Email Verification'
                from_email = settings.DEFAULT_FROM_EMAIL
                recipient_list = [self.email]
                sent_mail = send_mail(
                            subject,
                            txt_,
                            from_email,
                            recipient_list,
                            html_message=html_,
                            fail_silently=False,
                    )
                return sent_mail
        return False



def pre_save_email_activation(sender, instance, *args, **kwargs):
    if not instance.activated and not instance.forced_expired:
        if not instance.key:
            instance.key = unique_key_generator(instance)

pre_save.connect(pre_save_email_activation, sender=EmailActivation)


def post_save_user_create_reciever(sender, instance, created, *args, **kwargs):
    if created:
        obj = EmailActivation.objects.create(user=instance, email=instance.email)
        obj.send_activation()

post_save.connect(post_save_user_create_reciever, sender=User)


class File(models.Model):
    teacher = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    file = models.FileField(upload_to='media_/files/')
    uploaded_at = models.DateTimeField(auto_now_add=True)









































class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #dob = models.DateField(null=True,blank=True)
    bio  =models.TextField(null=True,blank=True)
    college = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return str(self.user.email)


class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    department = models.CharField(max_length=255)
    

class General(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone = models.IntegerField(null=True,blank=True)
    pincode = models.IntegerField(null=True,blank=True)
    city = models.CharField(max_length=255)

accounts/views/general.py
from django.shortcuts import redirect, render

from ..forms import  generalSignUpForm,GeneralExtraForm
from ..models import User


def GeneralSignup(request):
    if request.method == "POST":
        form1 = generalSignUpForm(request.POST or None)
        form2 = GeneralExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_general = True
            ins.is_active = False
            ins.save()

            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = generalSignUpForm()
        form2 = GeneralExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/views/home1.py
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:welcome')
        else:
            return redirect('students:welcome')
    return render(request, 'accounts/hom')

accounts/views/students.py
from django.shortcuts import  redirect, render

from ..forms import  StudentSignUpForm,StudentExtraForm
from ..models import   User



def StudentSignup(request):
    if request.method == "POST":
        form1 = StudentSignUpForm(request.POST or None)
        form2 = StudentExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_student = True
            ins.is_active =False
            ins.save()

            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = StudentSignUpForm()
        form2 = StudentExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/views/teachers.py
from django.shortcuts import  redirect, render

from ..forms import TeacherSignUpForm,TeacherExtraForm
from ..models import  User



def TeacherSignup(request):
    if request.method == "POST":
        form1 = TeacherSignUpForm(request.POST or None)
        form2 = TeacherExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_teacher = True
            ins.is_active = False

            ins.save()
            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = TeacherSignUpForm()
        form2 = TeacherExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/templates/accounts/borrowed_book.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{%load count_tags %}
<div class="container">
  <div class="col-sm-7" style="padding-left:30%">
    {% for book in books %}
        <a href="{% url 'payment:payment' book.id%}">{{ book.book_name }} <span class="badge" style="float:right;background-color:blue">{% finecal book.id%}</span></a>
    {% endfor %}
  </div>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% url 'accounts:change_password' as password_url %}
{% load crispy_forms_tags %}
{% block content %}
     <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .sign-up{
        background-color: ghostwhite;
    }
    .form-submit {
  width: 100%;
  border-radius: 5px;
  -webkit-border-radius: 5px;
  -o-border-radius: 5px;
  -ms-border-radius: 5px;
  padding: 17px 20px;
  box-sizing: border-box;
  font-size: 14px;
  font-weight: 700;
  color: #fff;
  text-transform: uppercase;
  border: none;

  background-image: -ms-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -o-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -webkit-linear-gradient(to left, #74ebd5, #9face6);
  background-image: linear-gradient(to left, #74ebd5, #9face6); }
    </style>
<div class=" container">
    <div class="col-md-8 col-sm-10 col-12 mx-auto">

{#      <form method="POST" novalidate>#}
{##}
{#        <input type="hidden" name="next" value="{{ next }}">#}
{#        {{ form }}#}
{#        <button type="submit" class="btn btn-success">Sign up</button>#}
{#      </form>#}


        <div class="card" style="background: ghostwhite;">

  <h2 class="card-header text-center py-3" style="color:white;background:black;font-family:'Lucida Handwriting';font-size: 35px;">
    <strong>Edit Profile</strong>
  </h2>


    <div class="card-body px-lg-5 pt-0">

    <!-- Form -->
    <form class="text-center" style="color: #757575;" action="" method="POST" novalidate enctype="multipart/form-data"> {% csrf_token %}


    {% crispy form %}
    </form>
    <!-- Form -->

  </div>

</div>

    <a href="{% url 'password_change' %}">Change Password</a>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/generalsignup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="main container">
             <link rel="stylesheet" href="{% static 'css/signup_style.css' %}">

            <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST"  action="" id="signup-form" class="signup-form">
                        <h2 class="form-title">Create account</h2>
                        {% csrf_token %}
                         <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="255" autofocus required id="id_email"></p>
<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" maxlength="255" required id="id_first_name"></p>
<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="255" id="id_last_name"></p>
<p><label for="id_password1">Password:</label> <input type="password" name="password1" required id="id_password1"> <span class="helptext"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></span></p>
<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" required id="id_password2"> <span class="helptext">Enter the same password as before, for verification.</span></p>
                        <p><label for="id_address">Address:</label> <input type="text" name="address" maxlength="255" required id="id_address"></p>
<p><label for="id_phone">Phone:</label> <input type="number" name="phone" id="id_phone"></p>
<p><label for="id_pincode">Pincode:</label> <input type="number" name="pincode" id="id_pincode"></p>
<p><label for="id_city">City:</label> <input type="text" name="city" maxlength="255" required id="id_city"></p>
                        <button type="submit" class="btn btn-success">Submit</button>

                    </form>

                    <p class="loginhere">
                        Have already an account ? <a href="{% url 'login' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>


        </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
     <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .login{
        background-color: ghostwhite;
    }
    .form-submit {
  width: 100%;
  border-radius: 5px;
  -webkit-border-radius: 5px;
  -o-border-radius: 5px;
  -ms-border-radius: 5px;
  padding: 17px 20px;
  box-sizing: border-box;
  font-size: 14px;
  font-weight: 700;
  color: #fff;
  text-transform: uppercase;
  border: none;

  background-image: -ms-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -o-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -webkit-linear-gradient(to left, #74ebd5, #9face6);
  background-image: linear-gradient(to left, #74ebd5, #9face6); }
    </style>
        <div class="main container">


<div class="col-7 mx-auto">
 <div class=" container">
{##}
{#        <input type="hidden" name="next" value="{{ next }}">#}
{#        {{ form }}#}
{#        <button type="submit" class="btn btn-success">Sign up</button>#}
{#      </form>#}


        <div class="card login">

  <h5 class="card-header  black-text text-center py-4" style="background: black;font-family:'Lucida Handwriting';font-size: 35px">
    <strong style="color: white;">Log In</strong>
  </h5>

  <!--Card content-->
  <div class="card-body px-lg-5 pt-0">

    <!-- Form -->
    <form class="text-center" style="color: #757575;" action="" method="POST" novalidate> {% csrf_token %}


    {% crispy form %}
    </form>

    <!-- Form -->
    <a href="{% url 'password_reset' %}"> reset</a>

  </div>

</div>

    </div>
</div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{#{% load crispy_forms_tags %}#}
{% block content %}
     <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .sign-up{
        background-color: ghostwhite;
    }

    </style>
<div class="container">
<br><br><br>
   <h1 class="card-header  black-text text-center py-4" style="font-family:'Lucida Handwriting';font-size: 35px">
    <strong style="color: black;font-family: 'Lucida Handwriting';">Profile</strong>
  </h1><br>
<div class="row">
    <div class="col-sm-4">
        {% if request.user.image %}
            <img src="{{ request.user.image.url }}" width="240">
        {% endif %}
    </div>
    <div class="col-sm-8" style="font-family: 'Comic Sans MS';font-size: 30px;">
        <p>Username: {{ request.user }}</p>
        <p>First name: {{ request.user.first_name }}</p>
        <p>Last name: {{ request.user.last_name }}</p>
        <p>Email: {{ request.user.email }}</p>
        <p>Phone: {{ request.user.phone_no }}</p>
        <p>number of books issued: {{ request.user.book_issued.count }}</p>

    </div>
</div>
</div>
{% endblock %}

accounts/templates/accounts/student_signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .sign-up{
        background-color: ghostwhite;

    .form-submit {
  width: 100%;
  border-radius: 5px;

  -moz-border-radius: 5px;

  -webkit-border-radius: 5px;
  -o-border-radius: 5px;
  -ms-border-radius: 5px;
  padding: 17px 20px;
  box-sizing: border-box;
  font-size: 14px;
  font-weight: 700;
  color: #fff;
  text-transform: uppercase;
  border: none;
  background-image: -ms-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -o-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -webkit-linear-gradient(to left, #74ebd5, #9face6);
  background-image: linear-gradient(to left, #74ebd5, #9face6); }

    ul{
        display: none;
    }
    </style>
        <div class="main container">



<form action=""  method="POST" class="sign-up col-7 mx-auto">
{% csrf_token %}
 <h5 class="card-header  black-text text-center py-4" style="background: black;font-family:'Lucida Handwriting';font-size: 35px">
    <strong style="color: white;">Sign Up</strong>
  </h5>
    <div class="col-7 mx-auto ">
    {% crispy form1 %}
    {% crispy form2 %}
        <br>
<button class="form-submit">click here</button>

 <p class="loginhere ">
                        Have already an account ? <a href="{% url 'login' %}" class="loginhere-link">Login here</a>
                    </p>
</div>

</form>



        </div>
{% endblock %}

accounts/templates/accounts/teachers_signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="main container">
             <link rel="stylesheet" href="{% static 'css/signup_style.css' %}">

            <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST"  action="" id="signup-form" class="signup-form">
                        <h2 class="form-title">Create account</h2>
                        {% csrf_token %}
                         <p><label for="id_email">Email:</label> <input type="email" name="email" maxlength="255" autofocus required id="id_email"></p>
<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" maxlength="255" required id="id_first_name"></p>
<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="255" id="id_last_name"></p>
<p><label for="id_password1">Password:</label> <input type="password" name="password1" required id="id_password1"> <span class="helptext"><ul><li>Your password can&#39;t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can&#39;t be a commonly used password.</li><li>Your password can&#39;t be entirely numeric.</li></ul></span></p>
<p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" required id="id_password2"> <span class="helptext">Enter the same password as before, for verification.</span></p>
                        <p><label for="id_department">Department:</label> <input type="text" name="department" maxlength="255" required id="id_department"></p>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>

                    <p class="loginhere">
                        Have already an account ? <a href="{% url 'login' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>


        </div>
{% endblock %}