bookcafe/urls.py
from django.contrib import admin
from django.urls import include,path

from .import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from . import views
from accounts.views.views import  LoginView


urlpatterns = [
    path("",views.home,name="home"),
    #path("home",views.home,name="home1"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),#accounts:logout


    path('admin/', admin.site.urls),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('category/', include(('category.urls', 'category'), namespace='category')),

    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('account/', include('accounts.passwords.urls')),
    path('search/', include(('search.urls', 'search'), namespace='search')),


#    path('cat1books/', include(('cat1books.urls', 'cat1books'), namespace='cat1books')),

    # notification part
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),

    path('donation/', include(('donation.urls', 'donation'), namespace='donation')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls','payment')),
    # path('paypal/',include('paypal.standard.ipn.urls')),
    # path('payment/',include('payment.urls','payment')),

    path('tokena/', include(('tokena.urls', 'tokena'), namespace='tokena')),

    path('del_borrower/', include(('del_borrower.urls', 'del_borrower'), namespace='del_borrower')),

    #path('feedback/', include('feedback_form.urls')),
    path('feedback/', include(('feedback_form.urls', 'feedback'), namespace='feedback')),
    path('contact/', include(('contactus.urls', 'contact'), namespace='contact')),

#     path('contactus/', include('contactus.urls'))
# submit
]

if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from django.urls import path
from .views import NotificationList,mark_all_read,mark_all_unread,delete_all_notification

app_name ='notification'
urlpatterns = [
    path('',NotificationList.as_view(),name = 'notifications_list'),
    path('markallasread/',mark_all_read,name="markallasread"),
    path('markallasunread/',mark_all_unread,name="markallasunread"),
    path('deletenotification/',delete_all_notification,name="deletenotification"),
]

tag/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('hashtag/', views.SearchTag.as_view(),name="ajax_search"),
    path('hashtag.json', views.TagJson.as_view()),
]

notification/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import User
from borrower.models import token,pooled_token
from events.models import borrower_detail

class NotificationQuerySet(models.query.QuerySet):
    ''' Notification QuerySet '''
    def unsent(self):
        return self.filter(emailed=False)

    def sent(self):
        return self.filter(emailed=True)

    def unread(self, include_deleted=False):
        """Return only unread items in the current queryset"""
        return self.filter(unread=True)

    def read(self, include_deleted=False):
        """Return only read items in the current queryset"""
        return self.filter(unread=False)

    def mark_all_as_read(self, recipient=None):
        """Mark as read any unread messages in the current queryset.
        Optionally, filter these by recipient first.
        """
        qset = self.unread(True)
        if recipient:
            qset = qset.filter(recipient=recipient)
        return qset.update(unread=False)

    def mark_all_as_unread(self, recipient=None):
        qset = self.read(True)
        if recipient:
            qset = qset.filter(recipient=recipient)
        return qset.update(unread = True)

    def mark_as_unsent(self, recipient=None):
        qset = self.sent()
        if recipient:
            qset = qset.filter(recipient=recipient)
        return qset.update(emailed=False)

    def mark_as_sent(self, recipient=None):
        qset = self.unsent()
        if recipient:
            qset = qset.filter(recipient=recipient)
        return qset.update(emailed=True)

class Notification(models.Model):
    #user to whom notification to be sent
    recipient = models.ForeignKey(User,default='',related_name='notifications',on_delete=models.CASCADE)
    unread = models.BooleanField(default=True, blank=False, db_index=True)
    notification_title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    emailed = models.BooleanField(default=False, db_index=True)
    description_view = models.BooleanField(default=False,db_index=True)
    objects = NotificationQuerySet.as_manager()


@receiver(post_save,sender = User)
def welcome_msg(sender,**kwargs):
    if kwargs['created']:
        Notification.objects.create(
            recipient = kwargs['instance'],
            notification_title = "Welcome to BOOKCAFE!!",
            description="thanks for signing up :)",
        )

@receiver(post_save,sender = token)
def sendnotification(sender,**kwargs):
    if(kwargs['created']):
        tokens = kwargs['instance']
        query = list()
        if tokens.user is not None:
            query.append(tokens.user)
        if tokens.user2 is not None:
            query.append(tokens.user2)
        if tokens.user3 is not None:
            query.append(tokens.user3)
        title = "token no. "+str(tokens.token)
        if len(query) > 1:
            title = ("token no. {} for pooled book").format(tokens.token)
        for user in query:
            Notification.objects.create(
                recipient = user,
                notification_title = title,
                description="your token no. "+str(tokens.token)+" for the book "+str(tokens.book)+".it will expire in 3 hours please go and collect before that",
            )

@receiver(post_save,sender = borrower_detail)
def welcome_msg(sender,**kwargs):
    if kwargs['created']:
        data = kwargs['instance']
        query = data.pooled_users.all()
        Notification.objects.create(
            recipient = data.name,
            notification_title = ("your book {} is issued").format(data.book_name),
            description="we have succesfully received your book issue comfirmation",
        )
        for user in query:
            Notification.objects.create(
                recipient = user,
                notification_title = ("your book {} is issued").format(data.book_name),
                description="we have succesfully received your book issue comfirmation",
            )

notification/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Notification
from accounts.models import User
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Notification

class NotificationList(LoginRequiredMixin,generic.ListView):
    """here we have all the notifications for a specific user"""
    template_name = 'notification/home.html'
    context_object_name = 'notifications'
    def get_queryset(self):
        #Notification.objects.mark_all_as_read(recipient = self.request.user)
        return Notification.objects.filter(recipient = self.request.user).order_by('timestamp').reverse()

def mark_all_read(request):
    user = request.user
    Notification.objects.mark_all_as_read(recipient = user)
    return HttpResponseRedirect(reverse('notification:notifications_list'))

def mark_all_unread(request):
    user = request.user
    Notification.objects.mark_all_as_unread(recipient = user)
    return HttpResponseRedirect(reverse('notification:notifications_list'))

def delete_all_notification(request):
    user = request.user
    qset = Notification.objects.filter(recipient = user)
    for notice in qset:
        qset.delete()
    return HttpResponseRedirect(reverse('notification:notifications_list'))

notification/templates/notification/home.html
{% extends "base.html" %}
{% load static %}
{%load count_tags %}
{%block content%}
{%load staticfiles%}
{% url "notification:markallasread" as mark_all_read%}
{% url "notification:markallasunread" as mark_all_unread%}
{% url "notification:deletenotification" as mark_all_delete %}

    <style>
    body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
    .sign-up{
        background-color: ghostwhite;
    }
    .form-submit {
  width: 100%;
  border-radius: 5px;
  -webkit-border-radius: 5px;
  -o-border-radius: 5px;
  -ms-border-radius: 5px;
  padding: 17px 20px;
  box-sizing: border-box;
  font-size: 14px;
  font-weight: 700;
  color: #fff;
  text-transform: uppercase;
  border: none;

  background-image: -ms-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -o-linear-gradient(to left, #74ebd5, #9face6);
  background-image: -webkit-linear-gradient(to left, #74ebd5, #9face6);
  background-image: linear-gradient(to left, #74ebd5, #9face6); }
    </style>
<div class="container-fluid" style="">

<div class="row">
  <div class="col-sm-3 px-5" >
    <h4>Settings</h4>
    <ul class="list-inline" style="font-weight:900;">
      <li><a href="{{mark_all_read}}">mark all as read </a></li>
      <li><a href="{{mark_all_unread}}">mark all as unread </a></li>
      <li><a href="{{mark_all_delete}}">delete all notification </a></li>
    </ul>
  </div>
  <div class="col-sm-6 border-left border-right" style="box-shadow: 5px 10px 10px #808080;">
    <h4 class="panel-heading">Notifications</h4><br>
    <ul class="table" style="font-weight:900;">
      {%for notice in notifications%}
        <li class="list-inline" onclick="myFunction({{notice.id}})" style="cursor:pointer">{{notice.notification_title}}</li>
        <p id="{{notice.id}}" style="display:none;font-weight:200">{{notice.description}}</p>
        <hr>
      {%endfor%}
    </ul>
  </div>
  <div class="col-sm-3">
  <h4>Details</h4><br>
  <ul class="list-inline" style="font-weight:900;">
    <li><span class="badge" style='background-color:red'>{%readtag%}</span> read</li>
    <li><span class="badge" style='background-color:red'>{%unreadtag%}</span> unread</li>
    <li><span class="badge" style='background-color:red'>{%emailedtag%}</span> emailed</li>
  </ul></div>
  </div>
  <script type="text/javascript">
    function myFunction(id){
      var bl = document.getElementById(id);
      s = bl.style.display;
      if(s == 'none'){
        bl.style.display = 'block';
      }
      else{
        bl.style.display = "none";
      }
    }
  </script>
</div>
{%endblock%}