accounts/passwords/urls.py
# accounts.passwords.urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),

url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

accounts/urls.py
from django.urls import path,re_path
from django.conf.urls import url

from .views import home1

from .views import views
from .views.students import StudentSignup
from .views.teachers import TeacherSignup
from .views.general import GeneralSignup
urlpatterns = [

    #path('', home1.home, name='home'),
    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$',
            views.AccountEmailActivateView.as_view(),
            name='email-activate'),
    path('studentsignup/', StudentSignup, name="student_signup_new"),
    path('teachersignup/', TeacherSignup, name="teacher_signup_new"),
    path('generalsignup/', GeneralSignup, name="general_signup_new"),

    path('signup/', home1.SignUpView.as_view(),name="signup_all"),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    url(r'^clear/$', views.clear_database, name='clear_database'),
    url(r'^progress-bar-upload/$', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    path('borrowed-books/', views.borrowed_books.as_view(), name='borrowed_books'),

]

bookcafe/urls.py
from django.contrib import admin
from django.urls import include,path

from .import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from . import views
from accounts.views.views import  LoginView


urlpatterns = [
    path("",views.home,name="home"),
    #path("home",views.home,name="home1"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),#accounts:logout


    path('admin/', admin.site.urls),
    path('book/', include(('book.urls', 'book'), namespace='book')),
    path('category/', include(('category.urls', 'category'), namespace='category')),

    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('account/', include('accounts.passwords.urls')),
    path('search/', include(('search.urls', 'search'), namespace='search')),


#    path('cat1books/', include(('cat1books.urls', 'cat1books'), namespace='cat1books')),

    # notification part
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),

    path('donation/', include(('donation.urls', 'donation'), namespace='donation')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls','payment')),
    # path('paypal/',include('paypal.standard.ipn.urls')),
    # path('payment/',include('payment.urls','payment')),

    path('tokena/', include(('tokena.urls', 'tokena'), namespace='tokena')),

    path('del_borrower/', include(('del_borrower.urls', 'del_borrower'), namespace='del_borrower')),

    #path('feedback/', include('feedback_form.urls')),
    path('feedback/', include(('feedback_form.urls', 'feedback'), namespace='feedback')),
    path('contact/', include(('contactus.urls', 'contact'), namespace='contact')),

#     path('contactus/', include('contactus.urls'))
# submit
]

if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tag/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('hashtag/', views.SearchTag.as_view(),name="ajax_search"),
    path('hashtag.json', views.TagJson.as_view()),
]

accounts/views/general.py
from django.shortcuts import redirect, render

from ..forms import  generalSignUpForm,GeneralExtraForm
from ..models import User


def GeneralSignup(request):
    if request.method == "POST":
        form1 = generalSignUpForm(request.POST or None)
        form2 = GeneralExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_general = True
            ins.is_active = False
            ins.save()

            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = generalSignUpForm()
        form2 = GeneralExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/views/home1.py
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:welcome')
        else:
            return redirect('students:welcome')
    return render(request, 'accounts/hom')

accounts/views/students.py
from django.shortcuts import  redirect, render

from ..forms import  StudentSignUpForm,StudentExtraForm
from ..models import   User



def StudentSignup(request):
    if request.method == "POST":
        form1 = StudentSignUpForm(request.POST or None)
        form2 = StudentExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_student = True
            ins.is_active =False
            ins.save()

            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = StudentSignUpForm()
        form2 = StudentExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/views/teachers.py
from django.shortcuts import  redirect, render

from ..forms import TeacherSignUpForm,TeacherExtraForm
from ..models import  User



def TeacherSignup(request):
    if request.method == "POST":
        form1 = TeacherSignUpForm(request.POST or None)
        form2 = TeacherExtraForm(request.POST or None)
        if form1.is_valid() and form2.is_valid():
            ins = form1.save(commit=False)
            ins.is_teacher = True
            ins.is_active = False

            ins.save()
            email = ins.email
            model_instance = form2.save(commit=False)
            user = User.objects.get(email=email)
            model_instance.user =user
            model_instance.save()
            return redirect('/')
    else:
        print("form is invalid")

        form1 = TeacherSignUpForm()
        form2 = TeacherExtraForm()
    return render(request,'accounts/student_signup.html',{"form1":form1,"form2":form2})

accounts/views/views.py
import time

from django.contrib import messages

from django.contrib.auth import authenticate, login
from django.views.generic import FormView,View,ListView
from django.shortcuts import reverse
from django.shortcuts import render, redirect
from django.http import JsonResponse

from accounts.models import File
from accounts.forms import FileForm

from accounts.models import EmailActivation
from accounts.forms import LoginForm, EditProfileForm
from events.models import borrower_detail
from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.safestring import mark_safe

class AccountEmailActivateView(View):
    def get(self, request, key, *args, **kwargs):
        qs = EmailActivation.objects.filter(key__iexact=key)
        confirm_qs = qs.confirmable()
        if confirm_qs.count() == 1:
            obj = confirm_qs.first()
            obj.activate()
            messages.success(request, "Your email has been confirmed. Please login.")
            return redirect("login")
        else:
            activated_qs = qs.filter(activated=True)
            if activated_qs.exists():
                reset_link = reverse("password_reset")
                msg = """Your email has already been confirmed
                Do you need to <a href="{link}">reset your password</a>?
                """.format(link=reset_link)
                messages.success(request, mark_safe(msg))
                return redirect("login")
        return render(request, 'registration/activation-error.html', {})

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        pass



class LoginView(FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    success_url = "/"

    def form_valid(self, form):
        request = self.request
        #for advance redirecction
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        return super(LoginView, self).form_invalid(form)





def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html',args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST , request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


class ProgressBarUploadView(View):
    def get(self, request):
        if request.user.is_teacher:
            file_list = File.objects.filter(teacher=request.user)
            return render(self.request, 'accounts/slides/base.html', {'files': file_list})
        else:
            return redirect('/')
    def post(self, request):
        if request.user.is_teacher:
            time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
            form = FileForm(self.request.POST, self.request.FILES)
            if form.is_valid():
                file = form.save(commit=False)
                file.teacher=request.user
                file.save()

                data = {'is_valid': True, 'name': file.file.name, 'url': file.file.url}
            else:
                data = {'is_valid': False}
            return JsonResponse(data)
        else:
            return redirect('/')



def clear_database(request):

    for file in File.objects.filter(teacher=request.user):
        file.file.delete()
        file.delete()
    return redirect(request.POST.get('next'))


class borrowed_books(LoginRequiredMixin,ListView):
    template_name = 'accounts/borrowed_book.html'
    context_object_name = 'books'
    def get_queryset(self):
        #Notification.objects.mark_all_as_read(recipient = self.request.user)
        return borrower_detail.objects.filter(name = self.request.user)

accounts/templates/accounts/slides/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BookCafe</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    <div class="container">
       <form method="POST" action="{% url 'accounts:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> Clear Database
    </button>
  </form>
  <h1 class="page-header">
   Slides
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">

        <div class="list-group">

          <a href="{% url 'accounts:progress_bar_upload' %}" class="list-group-item{% if request.path == '/photos/progress-bar-upload/' %} active{% endif %}">
             Upload Here
          </a>

        </div>
      </div>
    </div>
    <div class="col-md-9">
     <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload Files
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'accounts:progress_bar_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>sides</th>
      </tr>
    </thead>
    <tbody>
      {% for file in files %}
        <tr>
          <td><a href="{{ file.file.url }}">{{ file.file.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
  </div>
    </div>
    <script src="{% static 'js/jquery-3.1.1.min_file.js' %}"></script>
{#    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>#}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
   {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'file/js/progress-bar-upload.js' %}"></script>
  </body>
</html>

accounts/templates/accounts/slides/slides.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
        body{
    background-image: url('{% static "img/a1.jpg" %}');
    color: black;
    }
</style>
    <div class="container">




        {% for slide in slides %}
<a href="{{ slide.file.url }}">{{ slide.file.name }}</a>            <hr>
        {% endfor %}












    </div>









{% endblock %}